public class Cmroqd {
    public static void main() {
        System.out.println("fsmoa");
        System.out.println("dlxij");
        System.out.println("baaeb");
        System.out.println("gecye");
        System.out.println("wgrqd");
        System.out.println("lpyrv");
        System.out.println("vpbeq");
        System.out.println("vefig");
        System.out.println("okisa");
        System.out.println("kxehi");
        System.out.println("rleds");
        System.out.println("wfqeo");
        System.out.println("lqfyf");
        System.out.println("bucal");
        System.out.println("pkgdb");
        System.out.println("qveua");
        System.out.println("mhmts");
        System.out.println("ivqty");
        System.out.println("bjqqv");
        System.out.println("wmcxb");
        System.out.println("lxiaa");
        System.out.println("lyfgc");
        System.out.println("rhkwv");
        System.out.println("axxae");
        System.out.println("dylle");
        System.out.println("wliiv");
        System.out.println("oaxgn");
        System.out.println("rgmwt");
        System.out.println("ckafk");
        System.out.println("ynlhi");
    }
}
